server:
  port: 8082

# shardingsphere实现读写分离只需配置文件完成即可，
# spring boot自动装配会帮忙我们加载对应的Bean对象实现逻辑
spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 这里localhost需要写成从库的地址
        url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
      masterslave:
        # 负载均衡算法
        load-balance-algorithm-type: round_robin
        name: ms
        # 主库数据源名称
        master-data-source-name: master
        # 从库数据源名称
        slave-data-source-name: slave
      props:
        sql:
          show: true
