server:
  port: 8083

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    slave:
      url: jdbc:mysql://localhost:3306/slave?useUnicode=true&characterEncoding=utf8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456